# fly -t nono sp -c pipeline.yml -p BlabberTabber
# fly -t nono unpause-pipeline -p BlabberTabber
# fly -t nono expose-pipeline -p BlabberTabber
---
groups:
- name: BlabberTabber
  jobs:
  - unit
  - production-server
  - test-server
  - test-front-end

jobs:
- name: unit
  plan:
  - get: speech_broker
    trigger: true
  - task: unit-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: blabbertabber/golang-ginko
      inputs:
      - name: speech_broker
      run:
        path: speech_broker/ci/tasks/test-unit.sh
- name: test-front-end
  plan:
  - {get: diarizer_results, trigger: true}
  - {get: 6h,  trigger: true}
  - task: jest
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: blabbertabber/golang-ginko
      inputs:
      - name: diarizer_results
      run:
        path: npm
        args:
        - "test"
        dir: diarizer_results/js
- name: production-server
  plan:
  - {get: speech_broker, trigger: true}
  - {get: 6h,  trigger: true}
  - task: upload-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: blabbertabber/golang-ginko
      inputs:
      - name: speech_broker
      run:
        path: curl
        args:
        - "-F"
        - "meeting.wav=@/dev/null"
        - "-H"
        - "diarizer:Aalto"
        - "-H"
        - "transcriber:CMU Sphinx 4"
        - "https://diarizer.com:9443/api/v1/upload"
- name: test-server
  plan:
  - {get: speech_broker, trigger: true}
  - {get: 6h,  trigger: true}
  - task: upload-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: blabbertabber/golang-ginko
      inputs:
      - name: speech_broker
      run:
        path: curl
        args:
        - "-F"
        - "meeting.wav=@/dev/null"
        - "-H"
        - "diarizer:Aalto"
        - "-H"
        - "transcriber:CMU Sphinx 4"
        - "http://test.diarizer.com:8080/api/v1/upload"
resources:
- name: speech_broker
  type: git
  source:
    uri: https://github.com/blabbertabber/speechbroker
- name: diarizer_results
  type: git
  source:
    uri: https://github.com/blabbertabber/DiarizerResults
- name: 6h
  type: time
  source: {interval: 6h}
