# fly -t nono sp -c pipeline.yml -p BlabberTabber
# fly -t nono unpause-pipeline -p BlabberTabber
# fly -t nono expose-pipeline -p BlabberTabber
---
groups:
- name: BlabberTabber
  jobs:
  - unit
  - production-server
  - test-server

jobs:
- name: unit
  plan:
  - get: src
    trigger: true
  - task: unit-tests
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: blabbertabber/golang-ginko
      inputs:
      - name: src
      run:
        path: src/ci/tasks/test-unit.sh
- name: production-server
  plan:
  - {get: src, trigger: true}
  - {get: 6h,  trigger: true}
  - task: upload-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: blabbertabber/golang-ginko
      inputs:
      - name: src
      run:
        path: curl
        args:
        - "-F"
        - "meeting.wav=@/dev/null"
        - "-H"
        - "diarizer:Aalto"
        - "-H"
        - "transcriber:CMU Sphinx 4"
        - "https://diarizer.com:9443/api/v1/upload"
- name: test-server
  plan:
  - {get: src, trigger: true}
  - {get: 6h,  trigger: true}
  - task: upload-file
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: blabbertabber/golang-ginko
      inputs:
      - name: src
      run:
        path: curl
        args:
        - "-F"
        - "meeting.wav=@/dev/null"
        - "-H"
        - "diarizer:Aalto"
        - "-H"
        - "transcriber:CMU Sphinx 4"
        - "http://test.diarizer.com:8080/api/v1/upload"
resources:
- name: src
  type: git
  source:
    uri: https://github.com/blabbertabber/speechbroker
- name: 6h
  type: time
  source: {interval: 6h}